/**
 * Copyright (c) 2011 Brandon Aaron (http://brandonaaron.net) Mousewheel Plugin
 * Licensed under the MIT License (LICENSE.txt)
**/
(function(a){function d(b){var c=b||window.event,d=[].slice.call(arguments,1),e=0,f=!0,g=0,h=0;return b=a.event.fix(c),b.type="mousewheel",c.wheelDelta&&(e=c.wheelDelta/120),c.detail&&(e=-c.detail/3),h=e,c.axis!==undefined&&c.axis===c.HORIZONTAL_AXIS&&(h=0,g=-1*e),c.wheelDeltaY!==undefined&&(h=c.wheelDeltaY/120),c.wheelDeltaX!==undefined&&(g=-1*c.wheelDeltaX/120),d.unshift(b,e,g,h),(a.event.dispatch||a.event.handle).apply(this,d)}var b=["DOMMouseScroll","mousewheel"];if(a.event.fixHooks)for(var c=b.length;c;)a.event.fixHooks[b[--c]]=a.event.mouseHooks;a.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var a=b.length;a;)this.addEventListener(b[--a],d,!1);else this.onmousewheel=d},teardown:function(){if(this.removeEventListener)for(var a=b.length;a;)this.removeEventListener(b[--a],d,!1);else this.onmousewheel=null}},a.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);

/**
 * jQuery Easing v1.3
 * Animation smooth
**/
jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(e,a,c,b,d){return jQuery.easing[jQuery.easing.def](e,a,c,b,d)},easeInQuad:function(e,a,c,b,d){return b*(a/=d)*a+c},easeOutQuad:function(e,a,c,b,d){return-b*(a/=d)*(a-2)+c},easeInOutQuad:function(e,a,c,b,d){if((a/=d/2)<1)return b/2*a*a+c;return-b/2*(--a*(a-2)-1)+c},easeInCubic:function(e,a,c,b,d){return b*(a/=d)*a*a+c},easeOutCubic:function(e,a,c,b,d){return b*((a=a/d-1)*a*a+1)+c},easeInOutCubic:function(e,a,c,b,d){if((a/=d/2)<1)return b/
2*a*a*a+c;return b/2*((a-=2)*a*a+2)+c},easeInQuart:function(e,a,c,b,d){return b*(a/=d)*a*a*a+c},easeOutQuart:function(e,a,c,b,d){return-b*((a=a/d-1)*a*a*a-1)+c},easeInOutQuart:function(e,a,c,b,d){if((a/=d/2)<1)return b/2*a*a*a*a+c;return-b/2*((a-=2)*a*a*a-2)+c},easeInQuint:function(e,a,c,b,d){return b*(a/=d)*a*a*a*a+c},easeOutQuint:function(e,a,c,b,d){return b*((a=a/d-1)*a*a*a*a+1)+c},easeInOutQuint:function(e,a,c,b,d){if((a/=d/2)<1)return b/2*a*a*a*a*a+c;return b/2*((a-=2)*a*a*a*a+2)+c},easeInSine:function(e,
a,c,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+c},easeOutSine:function(e,a,c,b,d){return b*Math.sin(a/d*(Math.PI/2))+c},easeInOutSine:function(e,a,c,b,d){return-b/2*(Math.cos(Math.PI*a/d)-1)+c},easeInExpo:function(e,a,c,b,d){return a==0?c:b*Math.pow(2,10*(a/d-1))+c},easeOutExpo:function(e,a,c,b,d){return a==d?c+b:b*(-Math.pow(2,-10*a/d)+1)+c},easeInOutExpo:function(e,a,c,b,d){if(a==0)return c;if(a==d)return c+b;if((a/=d/2)<1)return b/2*Math.pow(2,10*(a-1))+c;return b/2*(-Math.pow(2,-10*--a)+2)+c},
easeInCirc:function(e,a,c,b,d){return-b*(Math.sqrt(1-(a/=d)*a)-1)+c},easeOutCirc:function(e,a,c,b,d){return b*Math.sqrt(1-(a=a/d-1)*a)+c},easeInOutCirc:function(e,a,c,b,d){if((a/=d/2)<1)return-b/2*(Math.sqrt(1-a*a)-1)+c;return b/2*(Math.sqrt(1-(a-=2)*a)+1)+c},easeInElastic:function(e,a,c,b,d){e=1.70158;var f=0,g=b;if(a==0)return c;if((a/=d)==1)return c+b;f||(f=d*0.3);if(g<Math.abs(b)){g=b;e=f/4}else e=f/(2*Math.PI)*Math.asin(b/g);return-(g*Math.pow(2,10*(a-=1))*Math.sin((a*d-e)*2*Math.PI/f))+c},easeOutElastic:function(e,
a,c,b,d){e=1.70158;var f=0,g=b;if(a==0)return c;if((a/=d)==1)return c+b;f||(f=d*0.3);if(g<Math.abs(b)){g=b;e=f/4}else e=f/(2*Math.PI)*Math.asin(b/g);return g*Math.pow(2,-10*a)*Math.sin((a*d-e)*2*Math.PI/f)+b+c},easeInOutElastic:function(e,a,c,b,d){e=1.70158;var f=0,g=b;if(a==0)return c;if((a/=d/2)==2)return c+b;f||(f=d*0.3*1.5);if(g<Math.abs(b)){g=b;e=f/4}else e=f/(2*Math.PI)*Math.asin(b/g);if(a<1)return-0.5*g*Math.pow(2,10*(a-=1))*Math.sin((a*d-e)*2*Math.PI/f)+c;return g*Math.pow(2,-10*(a-=1))*Math.sin((a*
d-e)*2*Math.PI/f)*0.5+b+c},easeInBack:function(e,a,c,b,d,f){if(f==undefined)f=1.70158;return b*(a/=d)*a*((f+1)*a-f)+c},easeOutBack:function(e,a,c,b,d,f){if(f==undefined)f=1.70158;return b*((a=a/d-1)*a*((f+1)*a+f)+1)+c},easeInOutBack:function(e,a,c,b,d,f){if(f==undefined)f=1.70158;if((a/=d/2)<1)return b/2*a*a*(((f*=1.525)+1)*a-f)+c;return b/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+c},easeInBounce:function(e,a,c,b,d){return b-jQuery.easing.easeOutBounce(e,d-a,0,b,d)+c},easeOutBounce:function(e,a,c,b,d){return(a/=
d)<1/2.75?b*7.5625*a*a+c:a<2/2.75?b*(7.5625*(a-=1.5/2.75)*a+0.75)+c:a<2.5/2.75?b*(7.5625*(a-=2.25/2.75)*a+0.9375)+c:b*(7.5625*(a-=2.625/2.75)*a+0.984375)+c},easeInOutBounce:function(e,a,c,b,d){if(a<d/2)return jQuery.easing.easeInBounce(e,a*2,0,b,d)*0.5+c;return jQuery.easing.easeOutBounce(e,a*2-d,0,b,d)*0.5+b*0.5+c}});

/**
 * Stellar.js v0.5.0 http://markdalgleish.com/projects/stellar.js
 * Copyright 2013, Mark Dalgleish
 * This content is released under the MIT license
 * http://markdalgleish.mit-license.org
**/
(function(f,g,v,h){function q(a,c){this.element=a;this.options=f.extend({},x,c);this._defaults=x;this._name=k;this.init()}var k="stellar",x={scrollProperty:"scroll",positionProperty:"position",horizontalScrolling:!0,verticalScrolling:!0,horizontalOffset:0,verticalOffset:0,responsive:!1,parallaxBackgrounds:!0,parallaxElements:!0,hideDistantElements:!0,hideElement:function(a){a.hide()},showElement:function(a){a.show()}},r={scroll:{getTop:function(a){return a.scrollTop()},setTop:function(a,c){a.scrollTop(c)},
getLeft:function(a){return a.scrollLeft()},setLeft:function(a,c){a.scrollLeft(c)}},position:{getTop:function(a){return-1*parseInt(a.css("top"),10)},setTop:function(a,c){a.css("top",c)},getLeft:function(a){return-1*parseInt(a.css("left"),10)},setLeft:function(a,c){a.css("left",c)}},margin:{getTop:function(a){return-1*parseInt(a.css("margin-top"),10)},setTop:function(a,c){a.css("margin-top",c)},getLeft:function(a){return-1*parseInt(a.css("margin-left"),10)},setLeft:function(a,c){a.css("margin-left",
c)}},transform:{getTop:function(a){return"none"!==getComputedStyle(a[0])[n]?-1*parseInt(getComputedStyle(a[0])[n].match(/(-?[0-9]+)/g)[5],10):0},setTop:function(a,c){y(a,c,"Y")},getLeft:function(a){return"none"!==getComputedStyle(a[0])[n]?-1*parseInt(getComputedStyle(a[0])[n].match(/(-?[0-9]+)/g)[4],10):0},setLeft:function(a,c){y(a,c,"X")}}},z={position:{setTop:function(a,c){a.css("top",c)},setLeft:function(a,c){a.css("left",c)}},transform:{setPosition:function(a,c,b,d,e){a[0].style[n]="translate3d("+
(c-b||0)+"px, "+(d-e||0)+"px, 0)"}}},n=function(){var a=/^(Moz|Webkit|Khtml|O|ms|Icab)(?=[A-Z])/,c=v.getElementsByTagName("script")[0].style,b="",d;for(d in c)if(a.test(d)){b=d.match(a)[0];break}"WebkitOpacity"in c&&(b="Webkit");"KhtmlOpacity"in c&&(b="Khtml");return function(a){return b+(0<b.length?a.charAt(0).toUpperCase()+a.slice(1):a)}}()("transform"),A=v.createElement("div").style.backgroundPositionX!==h,w=function(){return A?function(a,c,b){a.css({"background-position-x":c,"background-position-y":b})}:
function(a,c,b){a.css("background-position",c+" "+b)}}(),B=function(){return A?function(a){return[a[0].style.backgroundPositionX,a[0].style.backgroundPositionY]}:function(a){return a.css("background-position").split(" ")}}(),y=function(a,c,b){var d=getComputedStyle(a[0])[n];if("none"===d)a[0].style[n]="translate"+b+"("+c+"px)";else{a=a[0].style;var e=n;var p=/(-?[0-9]+[.]?[0-9]*)/g;b="X"===b?5:6;-1===d.search(p)?c=d:(p=d.split(p),b=2*b-1,p[b]===h?c=d:(p[b]=c,c=p.join("")));a[e]=c}};q.prototype={init:function(){this.options.name=
k+"_"+Math.floor(1E4*Math.random());this._defineElements();this._defineGetters();this._defineSetters();this._handleWindowLoadAndResize();this._detectViewport();this.refresh({firstLoad:!0});this._startAnimationLoop()},_defineElements:function(){this.element===v.body&&(this.element=g);this.$scrollElement=f(this.element);this.$element=this.element===g?f("body"):this.$scrollElement;this.$viewportElement=this.options.viewportElement!==h?f(this.options.viewportElement):this.$scrollElement[0]===g||0===this.options.scrollProperty.indexOf("scroll")?
this.$scrollElement:this.$scrollElement.parent()},_defineGetters:function(){var a=this;this._getScrollLeft=function(){return r[a.options.scrollProperty].getLeft(a.$scrollElement)};this._getScrollTop=function(){return r[a.options.scrollProperty].getTop(a.$scrollElement)}},_defineSetters:function(){var a=this,c=z[a.options.positionProperty];this._setScrollLeft=function(b){r[a.options.scrollProperty].setLeft(a.$scrollElement,b)};this._setScrollTop=function(b){r[a.options.scrollProperty].setTop(a.$scrollElement,
b)};this._setPosition=c.setPosition||function(b,d,e,p,f){a.options.horizontalScrolling&&c.setLeft(b,d,e);a.options.verticalScrolling&&c.setTop(b,p,f)}},_handleWindowLoadAndResize:function(){var a=this,c=f(g);a.options.responsive&&c.bind("load."+this.name,function(){a.refresh()});c.bind("resize."+this.name,function(){a._detectViewport();a.options.responsive&&a.refresh()})},refresh:function(a){var c=this,b=c._getScrollLeft(),d=c._getScrollTop();this._setScrollLeft(0);this._setScrollTop(0);this._setOffsets();
this._findParticles();this._findBackgrounds();a&&a.firstLoad&&/WebKit/.test(navigator.userAgent)&&f(g).load(function(){var a=c._getScrollLeft(),b=c._getScrollTop();c._setScrollLeft(a+1);c._setScrollTop(b+1);c._setScrollLeft(a);c._setScrollTop(b)});c._setScrollLeft(b);c._setScrollTop(d)},_detectViewport:function(){var a=this.$viewportElement.offset(),c=null!==a&&a!==h;this.viewportWidth=this.$viewportElement.width();this.viewportHeight=this.$viewportElement.height();this.viewportOffsetTop=c?a.top:
0;this.viewportOffsetLeft=c?a.left:0},_findParticles:function(){var a=this;this._getScrollLeft();this._getScrollTop();if(this.particles!==h)for(var c=this.particles.length-1;0<=c;c--)this.particles[c].$element.data("stellar-elementIsActive",h);this.particles=[];this.options.parallaxElements&&this.$element.find("[data-stellar-ratio]").each(function(b){b=f(this);var c,e,p,g,u,m,k,l=0,n=0,t=0,s=0;if(!b.data("stellar-elementIsActive"))b.data("stellar-elementIsActive",this);else if(b.data("stellar-elementIsActive")!==
this)return;a.options.showElement(b);b.data("stellar-startingLeft")?(b.css("left",b.data("stellar-startingLeft")),b.css("top",b.data("stellar-startingTop"))):(b.data("stellar-startingLeft",b.css("left")),b.data("stellar-startingTop",b.css("top")));p=b.position().left;g=b.position().top;u="auto"===b.css("margin-left")?0:parseInt(b.css("margin-left"),10);c="auto"===b.css("margin-top")?0:parseInt(b.css("margin-top"),10);u=b.offset().left-u;k=b.offset().top-c;b.parents().each(function(){var a=f(this);
if(!0===a.data("stellar-offset-parent"))return l=t,n=s,m=a,!1;t+=a.position().left;s+=a.position().top});c=b.data("stellar-horizontal-offset")!==h?b.data("stellar-horizontal-offset"):m!==h&&m.data("stellar-horizontal-offset")!==h?m.data("stellar-horizontal-offset"):a.horizontalOffset;e=b.data("stellar-vertical-offset")!==h?b.data("stellar-vertical-offset"):m!==h&&m.data("stellar-vertical-offset")!==h?m.data("stellar-vertical-offset"):a.verticalOffset;a.particles.push({$element:b,$offsetParent:m,isFixed:"fixed"===
b.css("position"),horizontalOffset:c,verticalOffset:e,startingPositionLeft:p,startingPositionTop:g,startingOffsetLeft:u,startingOffsetTop:k,parentOffsetLeft:l,parentOffsetTop:n,stellarRatio:b.data("stellar-ratio")!==h?b.data("stellar-ratio"):1,width:b.outerWidth(!0),height:b.outerHeight(!0),isHidden:!1})})},_findBackgrounds:function(){var a=this,c=this._getScrollLeft(),b=this._getScrollTop(),d;this.backgrounds=[];this.options.parallaxBackgrounds&&(d=this.$element.find("[data-stellar-background-ratio]"),
this.$element.is("[data-stellar-background-ratio]")&&d.add(this.$element),d.each(function(){var e=f(this),d=B(e),g,k,m,n,l,r=0,t=0,s=0,q=0;if(!e.data("stellar-backgroundIsActive"))e.data("stellar-backgroundIsActive",this);else if(e.data("stellar-backgroundIsActive")!==this)return;e.data("stellar-backgroundStartingLeft")?w(e,e.data("stellar-backgroundStartingLeft"),e.data("stellar-backgroundStartingTop")):(e.data("stellar-backgroundStartingLeft",d[0]),e.data("stellar-backgroundStartingTop",d[1]));
m="auto"===e.css("margin-left")?0:parseInt(e.css("margin-left"),10);g="auto"===e.css("margin-top")?0:parseInt(e.css("margin-top"),10);m=e.offset().left-m-c;n=e.offset().top-g-b;e.parents().each(function(){var a=f(this);if(!0===a.data("stellar-offset-parent"))return r=s,t=q,l=a,!1;s+=a.position().left;q+=a.position().top});g=e.data("stellar-horizontal-offset")!==h?e.data("stellar-horizontal-offset"):l!==h&&l.data("stellar-horizontal-offset")!==h?l.data("stellar-horizontal-offset"):a.horizontalOffset;
k=e.data("stellar-vertical-offset")!==h?e.data("stellar-vertical-offset"):l!==h&&l.data("stellar-vertical-offset")!==h?l.data("stellar-vertical-offset"):a.verticalOffset;a.backgrounds.push({$element:e,$offsetParent:l,isFixed:"fixed"===e.css("background-attachment"),horizontalOffset:g,verticalOffset:k,startingValueLeft:d[0],startingValueTop:d[1],startingBackgroundPositionLeft:isNaN(parseInt(d[0],10))?0:parseInt(d[0],10),startingBackgroundPositionTop:isNaN(parseInt(d[1],10))?0:parseInt(d[1],10),startingPositionLeft:e.position().left,
startingPositionTop:e.position().top,startingOffsetLeft:m,startingOffsetTop:n,parentOffsetLeft:r,parentOffsetTop:t,stellarRatio:e.data("stellar-background-ratio")===h?1:e.data("stellar-background-ratio")})}))},destroy:function(){var a,c,b,d;for(d=this.particles.length-1;0<=d;d--)a=this.particles[d],c=a.$element.data("stellar-startingLeft"),b=a.$element.data("stellar-startingTop"),this._setPosition(a.$element,c,c,b,b),this.options.showElement(a.$element),a.$element.data("stellar-startingLeft",null).data("stellar-elementIsActive",
null).data("stellar-backgroundIsActive",null);for(d=this.backgrounds.length-1;0<=d;d--)a=this.backgrounds[d],w(a.$element,a.startingValueLeft,a.startingValueTop);this._animationLoop=f.noop;f(g).unbind("load."+this.name).unbind("resize."+this.name)},_setOffsets:function(){var a=this,c=f(g);c.unbind("resize.horizontal-"+this.name).unbind("resize.vertical-"+this.name);"function"===typeof this.options.horizontalOffset?(this.horizontalOffset=this.options.horizontalOffset(),c.bind("resize.horizontal-"+
this.name,function(){a.horizontalOffset=a.options.horizontalOffset()})):this.horizontalOffset=this.options.horizontalOffset;"function"===typeof this.options.verticalOffset?(this.verticalOffset=this.options.verticalOffset(),c.bind("resize.vertical-"+this.name,function(){a.verticalOffset=a.options.verticalOffset()})):this.verticalOffset=this.options.verticalOffset},_repositionElements:function(){var a=this._getScrollLeft(),c=this._getScrollTop(),b,d,e,f=e=!0,g,h,m,k,l;if(this.currentScrollLeft!==a||
this.currentScrollTop!==c||this.currentWidth!==this.viewportWidth||this.currentHeight!==this.viewportHeight){this.currentScrollLeft=a;this.currentScrollTop=c;this.currentWidth=this.viewportWidth;this.currentHeight=this.viewportHeight;for(l=this.particles.length-1;0<=l;l--)b=this.particles[l],d=b.isFixed?1:0,this.options.horizontalScrolling&&(g=(a+b.horizontalOffset+this.viewportOffsetLeft+b.startingPositionLeft-b.startingOffsetLeft+b.parentOffsetLeft)*-(b.stellarRatio+d-1)+b.startingPositionLeft,
m=g-b.startingPositionLeft+b.startingOffsetLeft),this.options.verticalScrolling&&(h=(c+b.verticalOffset+this.viewportOffsetTop+b.startingPositionTop-b.startingOffsetTop+b.parentOffsetTop)*-(b.stellarRatio+d-1)+b.startingPositionTop,k=h-b.startingPositionTop+b.startingOffsetTop),this.options.hideDistantElements&&(f=!this.options.horizontalScrolling||m+b.width>(b.isFixed?0:a)&&m<(b.isFixed?0:a)+this.viewportWidth+this.viewportOffsetLeft,e=!this.options.verticalScrolling||k+b.height>(b.isFixed?0:c)&&
k<(b.isFixed?0:c)+this.viewportHeight+this.viewportOffsetTop),f&&e?(b.isHidden&&(this.options.showElement(b.$element),b.isHidden=!1),this._setPosition(b.$element,g,b.startingPositionLeft,h,b.startingPositionTop)):b.isHidden||(this.options.hideElement(b.$element),b.isHidden=!0);for(l=this.backgrounds.length-1;0<=l;l--)b=this.backgrounds[l],d=b.isFixed?0:1,e=this.options.horizontalScrolling?(a+b.horizontalOffset-this.viewportOffsetLeft-b.startingOffsetLeft+b.parentOffsetLeft-b.startingBackgroundPositionLeft)*
(d-b.stellarRatio)+"px":b.startingValueLeft,d=this.options.verticalScrolling?(c+b.verticalOffset-this.viewportOffsetTop-b.startingOffsetTop+b.parentOffsetTop-b.startingBackgroundPositionTop)*(d-b.stellarRatio)+"px":b.startingValueTop,w(b.$element,e,d)}},_startAnimationLoop:function(){var a=this,c=function(){return g.requestAnimationFrame||g.webkitRequestAnimationFrame||g.mozRequestAnimationFrame||g.oRequestAnimationFrame||g.msRequestAnimationFrame||function(a,c){g.setTimeout(a,1E3/60)}}();this._animationLoop=
function(){c(a._animationLoop);a._repositionElements()};this._animationLoop()}};f.fn[k]=function(a){var c=arguments;if(a===h||"object"===typeof a)return this.each(function(){f.data(this,"plugin_"+k)||f.data(this,"plugin_"+k,new q(this,a))});if("string"===typeof a&&"_"!==a[0]&&"init"!==a)return this.each(function(){var b=f.data(this,"plugin_"+k);b instanceof q&&"function"===typeof b[a]&&b[a].apply(b,Array.prototype.slice.call(c,1));"destroy"===a&&f.data(this,"plugin_"+k,null)})};f[k]=function(a){var c=
f(g);return c.stellar.apply(c,Array.prototype.slice.call(arguments,0))};f[k].scrollProperty=r;f[k].positionProperty=z;g.Stellar=q})(jQuery,window,document);
